name: Update Flake

on:
  schedule:
    # every day at 8:15am UTC
    # bumped 15 minutes to make sure to capture neovim-nightly's daily flake update
    - cron: "1 8 * * *"
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210604_8e6ee1b/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix flake update --commit-lock-file
      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: "[automation] update flake dependencies"
